TMDB_API_KEY = "e06eb402091615e803b7638fb4568c97"
TMDB_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMDZlYjQwMjA5MTYxNWU4MDNiNzYzOGZiNDU2OGM5NyIsIm5iZiI6MTc0MzU4NzIwMS4xNjcsInN1YiI6IjY3ZWQwNzgxM2Q4ZTc0ZTUxODAxMmJjOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.pOJ9tUlQlNPbttiQpj8sQw-vXZn8E0UI88rsLspFT4g"
DVAM = "ea2dcee690e0af8bb04f37aa35b75075"
ACCOUNT_ID = 21921781
